Fix foreign keys
yiisoft/db-sqlite pull request #268
Opened 2023-08-02 09:01 UTC by Tigrov

* Fix multiple foreign keys referencing to one table
* Fix possible `null` columns for reference

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

2023-08-06 06:38 UTC, vjik reviewed
Should we mark `TableSchema::compositeForeignKey()` as deprecated and remove it in the next major version?

Seems, `TableSchemaInterface::compositeForeignKey()` [used only here](https://github.com/search?q=org%3Ayiisoft%20compositeForeignKey&type=code), and after merge of this PR can be marked as deprecated also.

2023-08-06 07:02 UTC, vjik requested changes
Also need line in changelog

2023-08-06 07:02 UTC, vjik commented on src/Schema.php
> +            $table->foreignKey($id, $foreignReference);
```suggestion
            $table->foreignKey($id, [$foreignKey->getForeignTableName(), ...$columnNames]);
```

2023-08-06 07:02 UTC, vjik commented on src/Schema.php
> +                        foreach ((array) $primaryKey->getColumnNames() as $i => $primaryKeyName) {
```suggestion
                        foreach ((array) $primaryKey->getColumnNames() as $i => $primaryKeyColumnName) {
```

2023-08-06 07:02 UTC, vjik commented on src/Schema.php
> +                $result[(int) $id] = $fk;
```suggestion
                $result[] = $fk;
```

`loadTableForeignKeys` returns non-indexed array of foreign keys, right?

2023-08-06 12:38 UTC, Tigrov commented on src/Schema.php
> +            $table->foreignKey($id, $foreignReference);
Yes, I tried this way but
> Prior to PHP 8.1, unpacking an array which has a string key is not supported

2023-08-06 12:53 UTC, Tigrov commented on src/Schema.php
> +                $result[(int) $id] = $fk;
Right, looks like need to store `$id` in `ForeignKeyConstraint::$name`

2023-08-06 19:34 UTC, vjik commented on CHANGELOG.md
> +- Bug #268: Fix foreign keys (@Tigrov)
```suggestion
- Bug #268: Fix foreign keys: support multiple foreign keys referencing to one table and possible null columns for reference (@Tigrov)
```

2023-08-06 19:34 UTC, vjik approved these changes

2023-08-21 08:31 UTC, terabytesoftw approved these changes

2023-08-21 08:31 UTC, merged